name: Update Repo Count Badge

on:
  schedule:
    - cron: "40 10 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get repository count
        id: repo_count
        run: |
          COUNT=$(curl -s https://api.github.com/users/${{ github.repository_owner }}/repos | jq '. | length')
          echo "repo_count=$COUNT" >> $GITHUB_ENV

      - name: Update Gist with new count
        run: |
          GIST_ID="1290f77e79e35af30b56b759f0d057f0"
          TOKEN="${{ secrets.GIST_SECRET }}"

          # Create updated JSON content
          JSON=$(jq -n --arg count "$repo_count" \
            '{"schemaVersion": 1, "label": "Public Repos", "message": $count, "color": "blue"}')

          # Update Gist
          curl -X PATCH "https://api.github.com/gists/$GIST_ID" \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "$(jq -n --argjson json "$JSON" '{"files": {"repo-count.json": {"content": $json | tostring}}}')"

          #-d "{\"files\": {\"repo-count.json\": {\"content\": \"$JSON\"}}}"
